application: rsoccerdb
version: 1
runtime: python27
api_version: 1
threadsafe: true
default_expiration: "1h"

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  mime_type: image/x-icon
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  mime_type: text/plain
- url: /css
  mime_type: text/css
  static_dir: static/css
- url: /img
  static_dir: static/img
- url: /js
  static_dir: static/js
- url: /static
  static_dir: static
- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest

builtins:
- appstats: on
- admin_redirect: on
- remote_api: on

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/git/.*
- ^(.*/)?.*/svn/.*
- ^(.*/)?.*/data/.*
- ^(.*/)?\..*
- ^(.*/)?README$
- ^(.*/)?.*\.bak$
- ^(.*/)?.*\.sh$
- ^(.*/)?.*\.sql3$
- ^(.*/)?.*\.md$